In [35]:
from db_update.db_connector import *
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import DBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [24]:
headlines_tuple = get_all_headlines()

headlines = []

for headline in headlines_tuple:
    headlines.append(headline[0])

In [ ]:
print(headlines)

In [ ]:
for x in headlines:
    print(x)
    
print(len(headlines))

In [25]:
vectorizer = CountVectorizer(min_df=3, stop_words='english')
bag_of_words = vectorizer.fit_transform(headlines)

In [26]:
print(bag_of_words.todense())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
svd = TruncatedSVD(n_components=2)
lsa = svd.fit_transform(bag_of_words)

In [28]:
topic_encoded_df = pd.DataFrame(lsa, columns = ["topic_1", "topic_2"])
topic_encoded_df["headline"] = headlines
print(topic_encoded_df[["headline", "topic_1", "topic_2"]])

                                              headline   topic_1   topic_2
0    Some doctor’s offices are charging patients fo...  0.000000  0.000000
1    Here’s why AT&T’s stock should be taken more s...  0.764207 -0.077378
2        Stocks fall as tech, rate-cut doubts creep in  0.239413  0.398240
3    Stock Market Today: S&P 500 Falls at Open, Bit...  1.088963  0.159206
4    Dow falls 100 points as Wall Street continues ...  0.239293 -0.068453
..                                                 ...       ...       ...
465  Match’s stock rises after WSJ report that Elli...  1.715840  0.359903
466  DigitalBridge, Silver Lake lead $6.4B investme...  0.060219  0.138132
467  Nevro laying off 63 employees; revenue to beat...  0.383419 -0.344817
468  Albertsons’ stock falls after earnings beat ex...  1.239530 -0.571719
469  Franklin Resources unit Lexington Partners rai...  0.012289 -0.024638

[470 rows x 3 columns]


In [29]:
dictionary = vectorizer.get_feature_names_out()
dictionary

array(['000', '10', '100', '14', '16', '2023', '2024', '217', '22', '222',
       '275', '28', '46', '48', '4b', '500', '50th', '51', '52', '63',
       '65', '7b', '80', 'according', 'accused', 'acquired', 'activist',
       'address', 'adds', 'adj', 'africa', 'agenda', 'ago', 'agrees',
       'ahead', 'ai', 'aid', 'albertsons', 'alivecor', 'alphabet', 'amc',
       'americans', 'amid', 'analyst', 'analysts', 'antitrust', 'apple',
       'assets', 'atlantic', 'attack', 'attempting', 'autoimmune', 'bank',
       'banking', 'banks', 'barrels', 'beat', 'berlin', 'bets', 'bid',
       'biden', 'big', 'billion', 'bitcoin', 'board', 'bond', 'boost',
       'brought', 'builders', 'building', 'builds', 'bull', 'business',
       'buy', 'buyers', 'buyout', 'calls', 'capital', 'car', 'cash',
       'cell', 'centers', 'central', 'ceo', 'chair', 'charles', 'chatbot',
       'china', 'chinese', 'chip', 'cisco', 'claim', 'claims', 'client',
       'coming', 'company', 'concentration', 'congress', '

In [30]:
encoding_matrix = pd.DataFrame(svd.components_,
                               index=['topic_1', 'topic_2'],
                               columns=dictionary).T
encoding_matrix

topic_1   topic_2
000      0.035775  0.087890
10       0.085260  0.022225
100      0.009987  0.007751
14       0.018258  0.056587
16       0.036665 -0.023999
...           ...       ...
years    0.009455  0.013142
yields   0.034213  0.074849
york     0.002345  0.001474
youtube  0.009807  0.021579
zoom     0.001788  0.002230

[446 rows x 2 columns]

In [31]:
encoding_matrix['abs_topic_1'] = np.abs(encoding_matrix['topic_1'])
encoding_matrix['abs_topic_2'] = np.abs(encoding_matrix['topic_2'])
encoding_matrix.sort_values('abs_topic_1', ascending=False)

topic_1   topic_2  abs_topic_1  abs_topic_2
stock    0.654478 -0.103318     0.654478     0.103318
report   0.296231  0.367718     0.296231     0.367718
rises    0.243141 -0.095428     0.243141     0.095428
beat     0.209626 -0.182099     0.209626     0.182099
jobs     0.186691  0.361289     0.186691     0.361289
...           ...       ...          ...          ...
passing  0.000052 -0.001175     0.000052     0.001175
lauds    0.000052 -0.001175     0.000052     0.001175
schumer  0.000052 -0.001175     0.000052     0.001175
sphere   0.000037  0.000079     0.000037     0.000079
dead     0.000037  0.000079     0.000037     0.000079

[446 rows x 4 columns]

In [32]:
encoding_matrix.sort_values('abs_topic_2', ascending=False)

topic_1   topic_2  abs_topic_1  abs_topic_2
report    0.296231  0.367718     0.296231     0.367718
jobs      0.186691  0.361289     0.186691     0.361289
forecast  0.130532 -0.258664     0.130532     0.258664
demand    0.068582 -0.198406     0.068582     0.198406
growth    0.057596 -0.190940     0.057596     0.190940
...            ...       ...          ...          ...
claim     0.000450  0.000054     0.000450     0.000054
coming    0.000074  0.000023     0.000074     0.000023
company   0.000665 -0.000012     0.000665     0.000012
sector    0.003314 -0.000003     0.003314     0.000003
right     0.000354  0.000001     0.000354     0.000001

[446 rows x 4 columns]

In [36]:
headlines_pd = pd.DataFrame(headlines)

In [42]:
headlines_pd

0
0    Some doctor’s offices are charging patients fo...
1    Here’s why AT&T’s stock should be taken more s...
2        Stocks fall as tech, rate-cut doubts creep in
3    Stock Market Today: S&P 500 Falls at Open, Bit...
4    Dow falls 100 points as Wall Street continues ...
..                                                 ...
465  Match’s stock rises after WSJ report that Elli...
466  DigitalBridge, Silver Lake lead $6.4B investme...
467  Nevro laying off 63 employees; revenue to beat...
468  Albertsons’ stock falls after earnings beat ex...
469  Franklin Resources unit Lexington Partners rai...

[470 rows x 1 columns]

In [43]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(headlines)

In [44]:
dbscan = DBSCAN(eps=1.0, min_samples=5)
dbscan.fit(vectors)

DBSCAN(eps=1.0)

In [45]:
cluster_labels = dbscan.labels_
coords = vectors.toarray()

In [49]:
print(cluster_labels)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  0 -1  1  2  1  2 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1  3 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  3 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1  1  2
  1  2 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  3 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  3 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

In [46]:
no_clusters = len(np.unique(cluster_labels) )
no_noise = np.sum(np.array(cluster_labels) == -1, axis=0)

print('Estimated no. of clusters: %d' % no_clusters)
print('Estimated no. of noise points: %d' % no_noise)

Estimated no. of clusters: 5
Estimated no. of noise points: 446


In [50]:
colors = list(map(lambda x: '#3b4cc0' if x == 1 else '#b40426', cluster_labels))
plt.scatter(x, y, c=colors, marker="o", picker=True)
plt.show()

NameError: name 'y' is not defined